Django_student_app/onlineapp/urls.py
from django.conf.urls import url


from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView

from onlineapp.view import *
from .view.college import *
from .view.students import *
from .view.auth import *
from .view.studentSerializerView import *
from .view.CollegeSerializerView import *
from rest_framework_jwt.views import *


app_name="onlineapp"



urlpatterns = [
    # path('', admin.site.urls),
    path('admin/', admin.site.urls),


    # path('colleges/',CollegeView.as_view(),name="colleges_html"),

    path('colleges/', CollegeListView.as_view(), name="collegeshtml"),
    path('colleges/<int:pk>', CollegeDetailView.as_view(), name="collegesmarks"),

    # path('collegesdetail/<acronym>', CollegeDetailView.as_view(), name="collegesmarks"),

    # path('studentForm/',AddStudent.as_view(),name="colleges_html"),

    path('colleges/add',CreateCollegeView.as_view(),name="add_college"),
    path('colleges/<int:pk>/edit',UpdateCollegeView.as_view(),name="edit_college"),
    path('colleges/<int:pk>/delete',DeleteCollegeView.as_view(),name="delete_college"),

    path('colleges/<int:college_id>/students/add',CreateStudentView.as_view(),name="add_student"),
    path('colleges/<int:college_id>/students/<int:pk>/edit',UpdateStudentView.as_view(),name="edit_student"),
    path('colleges/<int:college_id>/students/<int:pk>/delete',DeleteStudentView.as_view(),name="delete_student"),
    path('signup/',SignUpView.as_view(),name='signup'),

    path('login/',LoginView.as_view(),name='login'),
    path('logout/',logout_user,name='logout'),




    path('api/v1/college/',college_list,name='rest_college_list'),
    path('api/v1/college/<int:pk>/',college_detail,name='rest_college'),
    path('api/v1/college/<int:pk>/students/',AllStudentListApi.as_view(),name='rest_student'),
    path('api/v1/college/<int:pk>/students/<int:student_id>',StudentDetailApi.as_view(),name='college_student'),
    path('api/v1/api-auth-token/',obtain_jwt_token),


    url(r'^', TemplateView.as_view(template_name="index.html")),








    # path('',views.welcome),
    # path('hello/',views.hello, name='hello'),
    #
    # path('example/',views.some_view),
    # path('colleges/',views.college_details),
    # path('college/',views.colleges),
    # path('clg_index/', views.clg_index),
    # path('tic_tac_toe/',views.tic_tac_toe),
    # path('student_details/',views.student_details),
    # path('student_detail/',views.student_detail),
    # path('student_detail/<int:value>',views.student_detail),
    # path('student_total/',views.student_total),
    # path('clg_stats/<str:clg>',views.college_stats),
    # path('students/',views.students),
    # path('profile/<int:id>',views.Profile),
    # path('testsession/',views.test_session),
    # path('testing/',views.test)
    # path('welcome/', views.index,name='index')
]

Django_student_app/onlineproject/urls.py
from django.contrib import admin
from django.urls import path
# from onlineapp import views

from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView

urlpatterns = [

    path('admin/',admin.site.urls),
    path(r'',include('onlineapp.urls')),
    url(r'^', TemplateView.as_view(template_name="index.html")),

    # path(r'^api-auth/', include('rest_framework.urls'))

    # path(r'onlineapp/',include('onlineapp.urls')),

]




if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Django_student_app/onlineapp/models.py
from django.db import models


# Create your models here.


class College(models.Model):
    name = models.CharField(max_length=128)
    location = models.CharField(max_length=64)
    acronym = models.CharField(max_length=8)
    contact = models.EmailField()

    def __str__(self):
        return self.acronym


class Student(models.Model):
    name = models.CharField(max_length=128)
    dob = models.DateField(null=True, blank=True)
    email = models.EmailField()
    db_folder = models.CharField(max_length=50)
    dropped_out = models.BooleanField(default=False)

    college = models.ForeignKey(College, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class MockTest1(models.Model):
    problem1 = models.IntegerField()
    problem2 = models.IntegerField()
    problem3 = models.IntegerField()
    problem4 = models.IntegerField()
    total = models.IntegerField()
    student = models.OneToOneField(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"Student {self.student.name} marks"



class Teacher(models.Model):
    name = models.CharField(max_length=128)
    college = models.ForeignKey(College, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Django_student_app/onlineapp/templates/colleges.html
<table>
{% if c_object %}
   	 
    {% for college in c_object %}
    <tr>
        <td>{{college.name}}</td><td>{{college.name}}</td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>

Django_student_app/onlineapp/templates/onlineapp/colleges.html
<table>
{% if c_object %}
   	 
    {% for college in c_object %}
    <tr>
        <td>{{college.name}}</td><td>{{college.acronym}}</td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>

Django_student_app/onlineapp/templates/tic_tac_toe.html
<!DOCTYPE html>
<html>
<head> 
<title> Tic-Tac-Toe </title>    
<style>
    *{
        background-color:#baf2bc;
    }
    
    button {
    background-color:  cornflowerblue;
    border: 2;
    width:100px;
    background-color: #31e222;
    text-align: center;
    align-content: center;
    height: 100px;
    font-size: 50px;
    text-decoration-color: fuchsia; 
    cursor: grab;
}
    button:hover{
        background-color: orange;
    }
    
    table{
    margin: auto ;
    align-items: center;
    align-items: center;
    padding: inherit;
    align-content:center;    
    }
    #button_div{
     align-content: center;
    
    }
    
    #u_r{
        align:right;
        background-color: azure;
        font-size: 30px;
    }
    
    
    #container{
    font-size: 80px;
    text-align:center;
    color: maroon;
    }
    
    
    
</style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script>
var winner=0;
stack_top=-1;
var moves=0;   
var x_arr=new Array(10);
var y_arr=new Array(10);

var grid=new Array(3);
grid[0]=new Array(3);
grid[1]=new Array(3);
grid[2]=new Array(3);
currentPlayer=1;

for (var i=0; i<3; i++) {
  for (var j=0; j<3; j++) {
    grid[i][j]=0;
  }
}

console.log("hello");
        
        
function isGameOver() {
        for(var iter=0;iter<3 && winner==0;iter++)
            {
                if((grid[iter][0]==grid[iter][1]) &&( grid[iter][1]==grid[iter][2]) && grid[iter][0]!=0)
                {
                 winner=grid[iter][0]; 
                    break;
                }    
            }
        
        
        for(var iter=0;iter<3 && winner==0;iter++)
            {
                if((grid[0][iter]==grid[1][iter]) && (grid[1][iter]==grid[2][iter])&& grid[0][iter]!=0)
                {
                 winner=grid[0][iter]; 
                    break;
                }    
            }
        if(grid[0][0]==grid[1][1] && grid[1][1]==grid[2][2] && winner==0)
          winner=grid[0][0];
        if(grid[0][2]==grid[1][1] && grid[2][0]==grid[1][1] && winner==0)
          winner=grid[0][2];
        
        if(winner!=0)
            {
                console.log("winner is ");
                 console.log(winner);    
              return winner;
            }
    return 0;
            
        }
        
        
function clickCell(x,y) {
  if (grid[x][y]>0) {
    alert("select a valid option");
  } 
  else {
    if (currentPlayer==1) {
      document.getElementById("cell_"+x+"_"+y).style.color="#240be2";
      document.getElementById("cell_"+x+"_"+y).innerHTML="X";
    document.getElementById("container").innerHTML = "O Turn";
    x_arr[top]=x;
    y_arr[top]=y;
        stack_top=stack_top+1;
      grid[x][y]=1;
      currentPlayer=2;
    moves=moves+1;
    } else {
       document.getElementById("cell_"+x+"_"+y).style.color="rgba(237, 7, 15, 0.91)";
       document.getElementById("cell_"+x+"_"+y).innerHTML="O";
        document.getElementById("container").innerHTML = "X Turn";
        x_arr[top]=x;
        y_arr[top]=y;
        stack_top=stack_top+1;
      grid[x][y]=2;
      currentPlayer=1;
    moves=moves+1;
    }
  }
    var win=isGameOver();
  if(moves==9)
      {
        document.getElementById("container").innerHTML = "--------Draw Match------";    
          setTimeout(function () { location.reload(1); }, 5000);
          reset();
      }
  else if(win==1 || win==2)
    {
      document.getElementById("container").innerHTML = "Player "+isGameOver()+" WON";
        setTimeout(function () { location.reload(1); }, 5000);
      reset();
    }
}

        
function undo(){
    if(stack_top >= 0)
        {
            x=x_arr[top];
            y=y_arr[top];
            grid[x][y]=0;
            document.getElementById("cell_"+x+"_"+y).innerHTML=' ';
            stack_top--;
            moves=moves-1;
            if(currentPlayer==1)
                {
                    currentPlayer=1;
                }
            else if(currentPlayer==2)
                {
                    currentPlayer==2;    
                }
                
        }
}
            
function reset() {
for (var i=0; i<=2; i++) {
  for (var j=0; j<=2; j++) {
    grid[i][j]=0;
    document.getElementById("cell_"+i+"_"+j).innerHTML="&nbsp;";
  }
}
 currentPlayer=1;
  setTimeout(function () { location.reload(1); }, 5000);
}    
    
</script>

</head>
<body>


<div id='container'> X - O </div>

<table id='board'>
  <tr>
    <td><button id="cell_0_0" onClick="clickCell(0,0)">&nbsp;&nbsp</button></td>
    <td><button id="cell_0_1" onClick="clickCell(0,1)">&nbsp; </button></td>
    <td><button id="cell_0_2"onClick="clickCell(0,2)">&nbsp; </button></td>
  </tr>
  <tr>
    <td><button id="cell_1_0" onClick="clickCell(1,0)"> &nbsp;</button></td>
    <td><button id="cell_1_1" onClick="clickCell(1,1)">&nbsp;</button></td>
    <td><button  id="cell_1_2" onClick="clickCell(1,2)">&nbsp;</button></td>
  </tr>
  <tr>
     <td><button id="cell_2_0" onClick="clickCell(2,0)"> &nbsp;</button></td>
    <td><button id="cell_2_1" onClick="clickCell(2,1)">&nbsp;</button></td>
    <td><button id="cell_2_2" onClick="clickCell(2,2)">&nbsp;</button></td>
  </tr>
</table>
<div id='button_div'>
    <button id="u_r" onClick="undo()">Undo</button>
    <button id="u_r" onClick="redo()">Redo</button>
    </div>
             
</body>  
</html>

Django_student_app/templates/LoginForm.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
	<div class="cols-xs-6 cols-xs-offset-3">
		<form method="post">
			{% csrf_token %}
			<fieldset>
				<div class="form-group">
					<label for="{{ form.username.id_for_label }}">User Name</label>
					{{form.username}}
				</div>
				<div class="form-group">
					<label for="{{ form.password.id_for_label }}">Password</label>
					{{form.password}}
				</div>
				<input type="submit" value="submit"/>
				<div class="container" align="center">
					<a href="{% url 'onlineapp:signup' %}">SignUp Here</a>
				</div>
			</fieldset>
		</form>
	</div>
</div>

{% endblock %}

Django_student_app/templates/_base.html
<html>
<head>
	<meta charset="UTF-8">
	<title>{{Title}}</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="styles.css">
	<style type="text/css">
		.navbar-expand-lg {
     background-color: #5e90e0;
     border-color: #222222;
}
.button{
	margin-top: 100px;
}

</style>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark primary-color">

	{% if request.user.is_authenticated%}
<button class="btn btn-default active pull-right"  style="float:right; margin-top: 10px; margin-right: 10px;">
 <a href="{% url 'onlineapp:logout' %}">Logout</a></button>
{% endif %}

</nav>

<!-- <nav class="navbar navbar-inverse">




</nav> -->
<div class="container">

{% block content %}

{% endblock %}
</div>
</body>
</html>

Django_student_app/templates/base.html
<html>
<head>
	<meta charset="UTF-8">
	<title>{{Title}}</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
{{college.name}}
{% block content %}

{% endblock % }
</body>
</html>

Django_student_app/templates/clg_stats.html
	
{% extends "_base.html" %}

{% block content %}

<table class="table table-striped" =2 align=center>
	
<h1 align="center">Students of {{college_name}}</h1>
		<br>	
		 <br>
		 {% if 'onlineapp.add_student' in user_permissions %}
		 <button class="btn btn-default active"><a href="{{collegeID}}/students/add">Add Student</a></button>
		 {% endif %}
		 <br>
		 <br>
{% if students %}
	<thead class="thead-light">
	<tr><td>Student ID</td><td>Student Name</td><td>Total Marks</td>
		{% if 'onlineapp.delete_student' in user_permissions and 'onlineapp.change_student' in user_permissions %}
		<td colspan="2">Actions</td></tr>
		 {% endif %}
</thead>
    {% for student in students %}
    <tr>
    	<td>{{student.student__id}}</td>
        <td>{{student.student__name}}</td>
        <td>{{student.student__mocktest1__total}}</td>
 
        {% if 'onlineapp.delete_student' in user_permissions and 'onlineapp.change_student' in user_permissions %}
         <td><a href="{{student.id}}/students/{{student.student__id}}/edit">edit</a></td>
	     <td><a href="{{student.id}}/students/{{student.student__id}}/delete">delete</a></td>
	     {% endif %}
    </tr>
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>		
{% endblock %}

Django_student_app/templates/college.html
{% extends "_base.html" %}

{% block content %}
	<table class=" table-striped">
		 <h1 align="center">College Details</h1>
		 <br>
		 <br>
		 {% if 'onlineapp.add_college' in user_permissions %}
		 <button class="btn btn-default active"><a href="{% url 'onlineapp:add_college' %}">Add College</a></button>
		 {% endif %}
		 <br>
		 <br>
	{% if colleges %}
		<thead class="thead-light">
		<tr><td>College Name</td><td>Acronym</td>
		{% if 'onlineapp.change_college' in user_permissions or 'onlineapp.delete_college' in user_permissions %}
		<td colspan="2">Actions</td></tr> 
		{% endif %}
		</thead>
	    {% for college in colleges %}
	    <tr>
	    
	        <td><a href="{% url 'onlineapp:collegesmarks' college.id %}" > {{ college.name }}</a></td>
	        <td>{{college.acronym}}</td>
	        {% if 'onlineapp.change_college' in user_permissions %}
	        <td><a href="{% url 'onlineapp:collegesmarks' college.id %}/edit" >edit</a></td>
	        {% endif %}
	        {% if 'onlineapp.delete_college' in user_permissions %}
	        <td><a href="{% url 'onlineapp:collegesmarks' college.id %}/delete" >delete</a></td>
	        {% endif %}
	    </tr>
	    {% endfor %}
	    
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
	</table>
{% endblock %}

Django_student_app/templates/collegeForm.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
	<div class="cols-xs-6 cols-xs-offset-3">
		<form method="post">
			{% csrf_token %}
			<fieldset>
				<legend>Add Colleges</legend>
				<div class="form-group">
					<label for="{{ for.name.id_for_label }}">Name</label>
					{{form.name}}
				</div>
				<div class="form-group">
					<label for="{{ for.location.id_for_label }}">Location</label>
					{{form.location}}
				</div>
				<div class="form-group">
					<label for="{{ for.acronym.id_for_label }}">Acronym</label>
					{{form.acronym}}
				</div>
				<div class="form-group">
					<label for="{{ for.contact.id_for_label }}">contact</label>
					{{form.contact}}
				</div>
				<input type="submit" value="submit"/>
			</fieldset>
		</form>
	</div>
</div>

{% endblock %}

Django_student_app/templates/colleges.html
<table border=2 align=center>
{% if c_object %}
	<tr><td><h3>College Name</h3></td><td><h3>Acronym</h3></td></tr> 
    {% for college in c_object %}
    <tr>
        <td>{{college.name}}</td><td>{{college.acronym}}</td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>
	

Django_student_app/templates/profile.html
<html>

<head></head>   
<style>


    body, html {
        height: 100%;
        font-family: sans-serif;
    }



    table * {
      position: relative;
    }
    table td, table th {
      padding-left: 8px;
    }
    table thead tr {
      height: 60px;
      background: #a5a5a5;
    }
    table tbody tr {
      height: 50px;
    }
    table tbody tr:last-child {
      border: 0;
    }
    table td, table th {
      text-align: left;
    }
    tbody tr {
      font-family: OpenSans-Regular;
      font-size: 15px;
      color: #305080;
      line-height: 1.2;
      font-weight: unset;
    }

    tbody tr:hover {
      color: #555555;
      background-color: #f5f5f5;
      cursor: pointer;
    }


    tbody tr:nth-child(even) {
      background-color: #e5e5e5;
    }

    table {
      border-spacing: 1;
      border-collapse: collapse;
      background: white;
      border-radius: 10px;
      overflow: hidden;
      width: 80%;
      margin: 0 auto;
      position: relative;
    }

   

    
</style>
<script type="text/javascript">
      function myFunc(variable,marks){
       
            var s = document.getElementById(variable);
            s.innerHTML = marks;
    
            
        }

</script>
<body>
<table align=center>
<caption><h2>Student Profile</h2></caption>
{% if s_object %}
 {% for student in s_object %}
  <tr><td>ID</td><td>{{student.id}}</td></tr>
  <tr><td>Name</td><td>{{student.name}}</td></tr>
  <tr><td>Email</td><td>{{student.email}}</td></tr>
  <tr><td>DB Folder</td><td>{{student.db_folder}}</td></tr>
  <tr><td>College</td><td>{{student.college__name}}</td></tr>
  <tr><td>Problem1</td><td>{{student.mocktest1__problem1}}</td></tr>
  <tr><td>Problem2</td><td>{{student.mocktest1__problem2}}</td></tr>
  <tr><td>Problem3</td><td>{{student.mocktest1__problem3}}</td></tr>
  <tr><td>Problem4</td><td>{{student.mocktest1__problem4}}</td></tr>
  <tr><td>Total</td><td>{{student.mocktest1__total}}</td></tr>
  {% endfor %}
  
{% else %}
    <p>No Values are available.</p>
{% endif %}
</table>
</body>
</html>

Django_student_app/templates/sampletemplate.html
<html>
<head>
	<meta charset="UTF-8">
	<title>{{Title}}</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
{% block content %}
{% endblock % }
</body>
</html>

Django_student_app/templates/studentForm.html
{% extends "_base.html" %}

{% block content %}


<div class="container">
	<div class="cols-xs-6 cols-xs-offset-3">
		<form method="post">
			{% csrf_token %}
			<fieldset>
				<legend>Add Student</legend>

				<div class="form-group">
					<label for="{{ for.name.id_for_label }}">Name</label>
					{{student_form.name}}
				</div>
				<div class="form-group">
					<label for="{{ for.email.id_for_label }}">Email</label>
					{{student_form.email}}
				</div>
				<div class="form-group">
					<label for="{{ for.db_folder.id_for_label }}">Db Folder</label>
					{{student_form.db_folder}}
				</div>
				<div class="form-group" align="left">
					<label >Dropped out</label>
					{{student_form.dropped_out}}
				</div>

				<div class="form-group">
					<label for="{{ for.problem1.id_for_label }}">Problem1</label>
					{{test_form.problem1}}
				</div>
				<div class="form-group">
					<label for="{{ for.problem2.id_for_label }}">Problem2</label>
					{{test_form.problem2}}
				</div>
				<div class="form-group">
					<label for="{{ for.problem3.id_for_label }}">Problem3</label>
					{{test_form.problem3}}
				</div>
				<div class="form-group">
					<label for="{{ for.problem4.id_for_label }}">Problem4</label>
					{{test_form.problem4}}
				</div>
				

				<input type="submit" value="submit"/>
			</fieldset>
		</form>
	</div>
</div>

{% endblock %}

Django_student_app/templates/student_total.html
<html>

<head></head>   
<style>


    body, html {
        height: 100%;
        font-family: sans-serif;
    }



    table * {
      position: relative;
    }
    table td, table th {
      padding-left: 8px;
    }
    table thead tr {
      height: 60px;
      background: #a5a5a5;
    }
    table tbody tr {
      height: 50px;
    }
    table tbody tr:last-child {
      border: 0;
    }
    table td, table th {
      text-align: left;
    }
    tbody tr {
      font-family: OpenSans-Regular;
      font-size: 15px;
      color: #305080;
      line-height: 1.2;
      font-weight: unset;
    }

    tbody tr:hover {
      color: #555555;
      background-color: #f5f5f5;
      cursor: pointer;
    }


    tbody tr:nth-child(even) {
      background-color: #e5e5e5;
    }

    table {
      border-spacing: 1;
      border-collapse: collapse;
      background: white;
      border-radius: 10px;
      overflow: hidden;
      width: 80%;
      margin: 0 auto;
      position: relative;
    }

    button {
        outline: none !important;
        border: none;
        background: transparent;
    }

    button:hover {
        cursor: pointer;
    }

    
</style>
<script type="text/javascript">
      function myFunc(variable,marks){
       
            var s = document.getElementById(variable);
            s.innerHTML = marks;
    
            
        }

</script>
<body>
<table align=center>
{% if c_object %}
	<tr><td><h3>College Name</h3></td><td><h3>Email</h3></td><td><h3>Acronym</h3></td><td><h3>Total</h3></td><td><h3>Total</h3></td></tr> 
    {% for student in c_object %}
    <tr>
        <td >{{student.name}}</td>
        <td>{{student.email}}</td>
        <td>{{student.college__acronym}}</td>
        <td id={{student.id}}> </td>
        <td>
            {% if student.mocktest1__total %}
            <button onclick="myFunc( {{student.id}} , {{student.mocktest1__total}} );">Total</button>
            {% else %}
            <button>Total</button>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No Values are available.</p>
{% endif %}
</table>
</body>
</html>

Django_student_app/templates/studentdetail.html
<head>
     <link rel="stylesheet" type="text/css" href="main.css">
</head>
<table border=2 align=center>
{% if c_object %}
	<tr><td><h3>College Name</h3></td><td><h3>Email</h3></td><td><h3>Acronym</h3></td></tr> 
    {% for student in c_object %}
    <tr>
        <td>{{student.name}}</td>
        <td>{{student.email}}</td>
        <td>{{student.college__acronym}}</td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No Values     are available.</p>
{% endif %}
</table>
	

Django_student_app/templates/studentdetails.html
<!DOCTYPE html>
<html>
<head>
<style>


body, html {
	height: 100%;
	font-family: sans-serif;
}



table * {
  position: relative;
}
table td, table th {
  padding-left: 8px;
}
table thead tr {
  height: 60px;
  background: #36304a;
}
table tbody tr {
  height: 50px;
}
table tbody tr:last-child {
  border: 0;
}
table td, table th {
  text-align: left;
}
tbody tr {
  font-family: OpenSans-Regular;
  font-size: 15px;
  color: #305080;
  line-height: 1.2;
  font-weight: unset;
}

tbody tr:hover {
  color: #555555;
  background-color: #f5f5f5;
  cursor: pointer;
}


tbody tr:nth-child(even) {
  background-color: #f5f5f5;
}


table {
  border-spacing: 1;
  border-collapse: collapse;
  background: white;
  border-radius: 10px;
  overflow: hidden;
  width: 80%;
  margin: 0 auto;
  position: relative;
}

	
</style>

</head>
<body>
<table  align=center>
{% if c_object %}
	<tr><td><h3>College Name</h3></td><td><h3>Email</h3></td><td><h3>Acronym</h3></td></tr> 
    {% for student in c_object %}
    <tr>
        <td>{{student.name}}</td>
        <td>{{student.email}}</td>
        <td>{{student.college__acronym}}</td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
</table>	
</body>
</html>



	

Django_student_app/templates/students.html
<html>

<head></head>   
<style>


    body, html {
        height: 100%;
        font-family: sans-serif;
    }



    table * {
      position: relative;
    }
    table td, table th {
      padding-left: 8px;
    }
    table thead tr {
      height: 60px;
      background: #a5a5a5;
    }
    table tbody tr {
      height: 50px;
    }
    table tbody tr:last-child {
      border: 0;
    }
    table td, table th {
      text-align: left;
    }
    tbody tr {
      font-family: OpenSans-Regular;
      font-size: 15px;
      color: #305080;
      line-height: 1.2;
      font-weight: unset;
    }

    tbody tr:hover {
      color: #555555;
      background-color: #f5f5f5;
      cursor: pointer;
    }


    tbody tr:nth-child(even) {
      background-color: #e5e5e5;
    }

    table {
      border-spacing: 1;
      border-collapse: collapse;
      background: white;
      border-radius: 10px;
      overflow: hidden;
      width: 80%;
      margin: 0 auto;
      position: relative;
    }

   

    
</style>
<script type="text/javascript">
      function myFunc(variable,marks){
       
            var s = document.getElementById(variable);
            s.innerHTML = marks;
    
            
        }

</script>
<body>
<table align=center>
{% if s_object %}
	<tr><td><h3>ID</h3></td><td><h3>College Name</h3></td><td><h3>Email</h3></td><td><h3>DB Folder</h3></td><td><h3>College</h3></td></tr> 
    {% for student in s_object %}
    <tr>
        <td >{{student.id}}</td>
        <td >{{student.name}}</td>
        <td>{{student.email}}</td>
        <td>{{student.db_folder}}</td>
        <td>{{student.college__acronym}}</td>
        <td><button><a href="profile/{{student.id}}">Show Profile</a></button></td>
    </tr>
    {% endfor %}
    
{% else %}
    <p>No Values are available.</p>
{% endif %}
</table>
</body>
</html>